"""fix

Revision ID: 3f38cb0116e4
Revises: 862d6ad7fcc7
Create Date: 2025-11-19 06:43:32.306853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3f38cb0116e4'
down_revision: Union[str, Sequence[str], None] = '862d6ad7fcc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(utc_time())'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(utc_time())'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('components', 'parameters',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('components', 'compatibility',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('components', 'weight',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('components', 'color',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('components', 'material',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(op.f('orders_ibfk_1'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'quantity')
    op.drop_column('orders', 'total_price')
    op.drop_column('orders', 'product_id')
    op.alter_column('storage', 'rack',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('storage', 'rack',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.add_column('orders', sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('total_price', mysql.FLOAT(), nullable=True))
    op.add_column('orders', sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('orders_ibfk_1'), 'orders', 'products', ['product_id'], ['id'])
    op.alter_column('components', 'material',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('components', 'color',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('components', 'weight',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               nullable=True)
    op.alter_column('components', 'compatibility',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('components', 'parameters',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_table('order_items')
    # ### end Alembic commands ###
